// <auto-generated />
using System;
using API.DbOperations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(EntityFrameworkCoreDbContext))]
    partial class EntityFrameworkCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("API.DbOperations.Entities.ProjectTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Priority = 0,
                            Status = 0,
                            Text = "Add feature1.",
                            Time = new DateTime(2022, 12, 9, 12, 31, 1, 354, DateTimeKind.Local).AddTicks(6182)
                        },
                        new
                        {
                            Id = 2,
                            Priority = 1,
                            Status = 1,
                            Text = "Add feature2.",
                            Time = new DateTime(2022, 12, 9, 12, 31, 1, 356, DateTimeKind.Local).AddTicks(8086)
                        },
                        new
                        {
                            Id = 3,
                            Priority = 2,
                            Status = 2,
                            Text = "Add task1.",
                            Time = new DateTime(2022, 12, 9, 12, 31, 1, 356, DateTimeKind.Local).AddTicks(8117)
                        },
                        new
                        {
                            Id = 4,
                            Priority = 0,
                            Status = 3,
                            Text = "Add task2.",
                            Time = new DateTime(2022, 12, 9, 12, 31, 1, 356, DateTimeKind.Local).AddTicks(8121)
                        },
                        new
                        {
                            Id = 5,
                            Priority = 2,
                            Status = 0,
                            Text = "Fix bug1.",
                            Time = new DateTime(2022, 12, 9, 12, 31, 1, 356, DateTimeKind.Local).AddTicks(8124)
                        },
                        new
                        {
                            Id = 6,
                            Priority = 0,
                            Status = 3,
                            Text = "Fix or add bug2.",
                            Time = new DateTime(2022, 12, 9, 12, 31, 1, 356, DateTimeKind.Local).AddTicks(8132)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
